[package]
name = "pipeline"
version = "0.1.0"
edition = "2024"

[dependencies]
systema-client = {path = "../systema-client"}
embedding = {path = "../embedding"}
scraper.workspace = true
tracing.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
utilites.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true